development:
  dialect: mysql
  dir: db/migrations
  datasource: root:password@tcp(mysql)/test?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

test:
  dialect: mysql
  dir: db/migrations
  datasource: root:password@tcp(mysql)/test?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
  dialect: mysql
  dir: db/migrations
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_ADDRESS})/${DB_SCHEMA}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
